app:
  kafka:
    groupId: artingest
    topic:
      article:
        inbox: article-inbox
        outbox: article-outbox
  ollama:
    promptInstruction: |
      The last paragraph is a news article on a company laying off some employees.
      Extract from the article the following data:
        the company name that laid off the employees, 
        the number of laid-off employees, 
        the location where the layoff happened,
        the date when the layoff happened,
        the position that were impacted,
        the reason given for the layoff.
        Return the above data in the specified JSON schema format.
        \n


spring:
  application:
    name: artingest
  data:
    mongodb:
      auto-index-creation: true
  threads:
    virtual:
      enabled: true
